apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-api-gateway.yaml
  - deployment-hcx-apis.yaml
  - deployment-hcx-onboard.yaml
  - service-api-gateway.yaml
  - service-hcx-apis.yaml
  - service-hcx-onboard.yaml
  - configmap.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: hcx-platform
  app.kubernetes.io/managed-by: kustomize

